### ISSUE TITLE
On change microflow is broken

### ISSUE THREAD

**Issue by erikkg** [mendix/BarcodeScannerForPhoneGap#12]
Hi Andries,

It seems that the 'on change nanoflow' is working well but the 'on change microflow' is not working anymore since the new release. Is it possible to fix this quickly? We used the Mendix Developer app (old one) to trigger the QR code. Thanks.

Stack trace in Mendix when 'on change microflow' applied:

undefined is not an object (evaluating 'Object.keys(o)') keys@[native code]
callNanoflow@http://172.16.1.221:8080/mxclientsystem/mxui/mxui.js?636620856379736626:51:224231
_executeAction@http://172.16.1.221:8080/widgets/BarcodeScannerForPhoneGap/widget/BarcodeScannerForPhoneGap.js?636620856379736626:83:37
_barcodeSuccess@http://172.16.1.221:8080/widgets/BarcodeScannerForPhoneGap/widget/BarcodeScannerForPhoneGap.js?636620856379736626:58:36
_barcodeSuccess@[native code]
file:///var/containers/Bundle/Application/05ED71DD-2353-44DC-82E7-E6AED8F836C5/Mendix%20Developer%20App.app/www/plugins/phonegap-plugin-barcodescanner/www/barcodescanner.js:113:36
callbackFromNative@file:///var/containers/Bundle/Application/05ED71DD-2353-44DC-82E7-E6AED8F836C5/Mendix%20Developer%20App.app/www/cordova.js:293:63
nc2@file:///var/containers/Bundle/Application/05ED71DD-2353-44DC-82E7-E6AED8F836C5/Mendix%20Developer%20App.app/www/cordova.js:1046:39

**Comment by Andries-Smit** [comment]
Fixed in https://appstore.home.mendix.com/link/app/1469/ release 3.2.1
