### ISSUE TITLE
Barcode scanner returns an error on iOS

### ISSUE THREAD

**Issue by feddovanede** [mendix/BarcodeScannerForPhoneGap#16]
Clicking the barcode scanner button returns an error:
`Scanning failed: undefined`
Console remains empty.

![image](https://user-images.githubusercontent.com/36268709/49510913-f76b1c00-f889-11e8-9818-4fdb3024ac93.png)

**Comment by Andries-Smit** [comment]
Fixed in v3.2.2 and released in the app store https://appstore.home.mendix.com/link/app/1469/
We improved the error message.

Note the error was showing when the `NSCameraUsageDescription` was not set. See documentation how to fix it https://github.com/mendix/BarcodeScannerForPhoneGap#add-plugin
