### ISSUE TITLE
MxMobile App

### ISSUE THREAD

**Issue by RoelandSalij** [mendix/BarcodeScannerForPhoneGap#9]
It would be great if this widgets works out of the box with the Mx Mobile app.

**Comment by Andries-Smit** [comment]
There is a conflict between the plugins for QR scanner of the Mendix Mobile (demo) App and this widget. So unfortunately we cant make them work together. 
A custom build mobile apps create via sprintr works fine and the the old Mendix Developer App does till work with the scanner.

**Comment by pluxain** [comment]
Does this mean that whenever we want to test the integration of the plugin in our Mobile App we need to deploy it to a public App Store (Android or Apple) ?

**Comment by pluxain** [comment]
Sorry, I found the old Mendix Developer App and it works!

**Comment by KevinVlaanderen** [comment]
It does not. You do need to build your hybrid mobile app, but you do not need to publish it. Instead, for Android you can install the APK on any device directly. For iOS, you might consider using testflight to install test versions on your devices.

Alternatively, you can use the old developer app, as you already discovered ;)

**Comment by pluxain** [comment]
Thanks a lot for the informations. Much appreciated.
